on resource pack response:
	if the resource pack was successfully load:
		make player execute command "/screeneffect fullscreen BLACK 1 50 30 freeze self Welcome to Aegis"
on first join:
	execute console command "/rg addmem -w world tutorial_island %player%"

on first join:
	wait 1 seconds
	execute console command "/warp Tutorial %player%"

on first join:
	execute console command "/lp user %player% promote levels"

